export class DoctorsFakeData {
  public static doctors = [
    {
      id: 1,
      cmp: '08788787',
      tipo_doc: 'DNI',
      nro_doc: '43550011',
      fullName: 'Galen Slixby',
      role: 'Editor',
      telefono: '(479) 232-9151',
      otro_telefono: '-',
      celular: ' 992329151',
      especialidad: 'Cardiología',
      email: 'gslixby0@abc.net.au',
      status: 'inactive',
      avatar: ''
    },
    {
      id: 2,
      cmp: '08788787',
      tipo_doc: 'DNI',
      nro_doc: '43550011',
      fullName: 'Halsey Redmore',
      role: 'Author',
      telefono: '(479) 232-9151',
      otro_telefono: '-',
      celular: ' 992329151',
      especialidad: 'Odontología',
      email: 'hredmore1@imgur.com',
      status: 'pending',
      avatar: 'assets/images/avatars/10.png'
    },
    {
      id: 3,
      cmp: '08788787',
      tipo_doc: 'DNI',
      nro_doc: '43550011',
      fullName: 'Marjory Sicely',
      role: 'Maintainer',
      telefono: '(479) 232-9151',
      otro_telefono: '-',
      celular: ' 992329151',
      especialidad: 'Traumatología',
      email: 'msicely2@who.int',
      status: 'active',
      avatar: 'assets/images/avatars/1.png'
    },
    {
      id: 4,
      cmp: '08788787',
      tipo_doc: 'DNI',
      nro_doc: '43550011',
      fullName: 'Cyrill Risby',
      role: 'Maintainer',
      telefono: '(479) 232-9151',
      otro_telefono: '-',
      celular: ' 992329151',
      especialidad: 'Neumología',
      email: 'crisby3@wordpress.com',
      status: 'inactive',
      avatar: 'assets/images/avatars/9.png'
    },
    {
      id: 5,
      cmp: '08788787',
      tipo_doc: 'DNI',
      nro_doc: '43550011',
      fullName: 'Maggy Hurran',
      role: 'Subscriber',
      telefono: '(479) 232-9151',
      otro_telefono: '-',
      celular: ' 992329151',
      especialidad: 'Oftalmología',
      email: 'mhurran4@yahoo.co.jp',
      status: 'pending',
      avatar: 'assets/images/avatars/10.png'
    },
    {
      id: 6,
      cmp: '08788787',
      tipo_doc: 'DNI',
      nro_doc: '43550011',
      fullName: 'Silvain Halstead',
      role: 'Author',
      telefono: '(479) 232-9151',
      otro_telefono: '-',
      celular: ' 992329151',
      especialidad: 'Medicina Interna',
      email: 'shalstead5@shinystat.com',
      status: 'active',
      avatar: ''
    }
  ];
}
